---
prometheusOperator:
  createCustomResource: false
# Forcing Kubelet metrics scraping on http 
kubelet:
  enabled: true
  serviceMonitor:
    https: false
# Disabling scraping of Master Nodes Components
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false

# TODO: verfiy if this works. With default con
# prometheus:
#   prometheusSpec:
#     podMonitorSelector:
#       hazards.tt/monitoring: podMonitor


prometheus:

  server:
    persistentVolume:
      enabled: true

  prometheusSpec:
    prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    thanos:
      image: quay.io/thanos/thanos:v0.9.0
      version: v0.9.0
      objectStorageConfig:
        name: thanos
        key: object-store.yaml
    
    logLevel: debug